### ISSUE TITLE
Delete model should use modal

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#496]
The method of deleting models is a bit overkill. Instead of redirecting the user to a separate page, look into displaying a modal pop-up instead which handles the same process.

Issue generated from the following comment: https://github.com/QutEcoacoustics/workbench-client/pull/488#pullrequestreview-498515737

>the delete warning should not be a page, but a bootstrap modal shown on the details page
>
>    and shouldn't use a h1 for text
>    and shouldn't be a form

**Comment by hudson-newey** [comment]
At the moment, all confirmation modals are components of the harvest module.

Since we are going to be using a confirmation component in multiple locations e.g. delete project, delete region, delete site, cancel my account, etc...

We should probably move this component to the app shared components.

It appears that this is already being done (partially), as the `baw-harvest-confirmation-modal` is being used in the batch download component, however, I believe that if we are using this as a shared confirmation component, it should be located in the shared confirmation component folder location and tested as such.

As part of this ticket, I'm going to be moving / generalizing the harvest `confirmation.component.ts` to the shared app components.

_Edit: There is a better way to create these menu modals using the `modalMenu` interface and the revisions above will no longer be needed. I will be reverting my changes to prevent scope creep._

**Comment by hudson-newey** [comment]
Preliminary mock-ups (Subject to change)

![image](https://user-images.githubusercontent.com/33742269/219255384-979eba7d-1c0c-4e56-93fd-79b7e57ed476.png)
