### ISSUE TITLE
Azure Pipelines Staging Build

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#83]
Azure pipelines should output both a staging and production version of workbench-client.

**Comment by atruskie** [comment]
What's the difference?

The only thing I can think of is minimised vs not. Though with source maps this doesn't really matter.

Regardless this achievable by attaching extra assets to the build artefacts

**Comment by Allcharles** [comment]
The difference is which ecosounds server the application points to. Staging points to staging.ecosounds.org and Production points to www.ecosounds.org

**Comment by atruskie** [comment]
Nope; the server/API and other deployment variables are defined in and are changeable in the config JSON files.

The rub here (the problem) with the current setup is: _how do we know which config file to download and load?_

- (current solution): use `environment.xxx.ts` to download correct config
  - this needs multiple copies of the built app assets, each with a *single string* that is different
- use some kind of token-rewriting post-build step to customize each package 
- always download from the exact some URL `config.json` and rely on the deployment step to provide/change the values

I like the last choice because it means:

- we only ever build one version of the app
- we don't need to manipulate/build/post-process the built app per environment
- the staging and production apps are the same (which they should be) and only the configuration that is present on the server, with the deployed app assets, modifies the behaviour
- the a2o and ecosounds apps are the same... blah blah blah, see previous point
